#!/usr/bin/env python3
"""
Generate synthetic graph datasets for FVS benchmarking.

This script is idempotent:
- Existing files are kept unless --force is provided.
- Only missing graphs are generated by default.

Output folders:
- data/synthetic_benchmark/undirected/  (edge-list .txt)
- data/synthetic_benchmark/directed/    (edge-list .txt, if --directed)
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path
from typing import Iterable, List, Set, Tuple

import networkx as nx

PROJECT_ROOT = Path(__file__).resolve().parent.parent
UNDIR_OUT = PROJECT_ROOT / "data" / "synthetic_benchmark" / "undirected"
DIR_OUT = PROJECT_ROOT / "data" / "synthetic_benchmark" / "directed"

DEFAULT_SIZES = [10, 20, 50, 100, 200, 500, 1000]


def ensure_dirs() -> None:
    UNDIR_OUT.mkdir(parents=True, exist_ok=True)
    DIR_OUT.mkdir(parents=True, exist_ok=True)


def normalize_edges(edges: Iterable[Tuple[int, int]], directed: bool) -> List[Tuple[int, int]]:
    """Normalize and deduplicate edges to keep all generated files consistent."""
    seen: Set[Tuple[int, int]] = set()
    for u_raw, v_raw in edges:
        u = int(u_raw)
        v = int(v_raw)
        edge = (u, v) if directed else ((u, v) if u <= v else (v, u))
        seen.add(edge)
    return sorted(seen)


def write_edge_list(edges: Iterable[Tuple[int, int]], path: Path, directed: bool) -> None:
    with path.open("w", encoding="utf-8") as f:
        for u, v in normalize_edges(edges, directed=directed):
            f.write(f"{u} {v}\n")


def erdos_renyi(n: int) -> nx.Graph:
    p = min(0.25, max(0.02, 3.0 / max(2, n)))
    return nx.erdos_renyi_graph(n, p, seed=42 + n)


def barabasi_albert(n: int) -> nx.Graph:
    m = max(1, min(8, n // 10))
    return nx.barabasi_albert_graph(n, m, seed=100 + n)


def watts_strogatz(n: int) -> nx.Graph:
    k = max(2, min(10, n // 10))
    if k % 2 == 1:
        k += 1
    return nx.watts_strogatz_graph(n, k, 0.15, seed=200 + n)


def grid_graph(n: int) -> nx.Graph:
    # Build approximately n nodes using a rectangle.
    rows = int(n**0.5)
    cols = max(1, n // max(1, rows))
    g = nx.grid_2d_graph(rows, cols)
    # Relabel to integer node ids for simple edge list format.
    return nx.convert_node_labels_to_integers(g)


def tree_graph(n: int) -> nx.Graph:
    # networkx>=3.4 removed random_tree in favor of random_labeled_tree.
    if hasattr(nx, "random_labeled_tree"):
        return nx.random_labeled_tree(n, seed=300 + n)
    return nx.random_tree(n, seed=300 + n)


def orient_graph_randomly(g: nx.Graph, seed: int) -> nx.DiGraph:
    rng = random.Random(seed)
    d = nx.DiGraph()
    d.add_nodes_from(g.nodes())
    for u, v in g.edges():
        if rng.random() < 0.5:
            d.add_edge(u, v)
        else:
            d.add_edge(v, u)
    return d


def generate_for_size(n: int) -> List[Tuple[str, nx.Graph]]:
    return [
        ("erdos_renyi", erdos_renyi(n)),
        ("barabasi_albert", barabasi_albert(n)),
        ("watts_strogatz", watts_strogatz(n)),
        ("grid", grid_graph(n)),
        ("tree", tree_graph(n)),
    ]


def maybe_write_graph(
    graph_name: str,
    n: int,
    graph_obj: nx.Graph,
    directed: bool,
    force: bool,
) -> Tuple[bool, Path]:
    out_dir = DIR_OUT if directed else UNDIR_OUT
    suffix = "directed" if directed else "undirected"
    out_path = out_dir / f"{graph_name}_n{n}_{suffix}.txt"

    if out_path.exists() and not force:
        return False, out_path

    if directed:
        d = orient_graph_randomly(graph_obj, seed=500 + n)
        write_edge_list(d.edges(), out_path, directed=True)
    else:
        write_edge_list(graph_obj.edges(), out_path, directed=False)

    return True, out_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate synthetic edge-list benchmark graphs")
    parser.add_argument(
        "--sizes",
        nargs="*",
        type=int,
        default=DEFAULT_SIZES,
        help="Vertex sizes to generate (default: 10 20 50 100 200 500 1000)",
    )
    parser.add_argument(
        "--directed",
        action="store_true",
        help="Also generate directed versions in data/synthetic_benchmark/directed/",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing files instead of skipping",
    )
    args = parser.parse_args()

    ensure_dirs()

    created = 0
    skipped = 0

    for n in args.sizes:
        if n <= 1:
            print(f"[SKIP] invalid size n={n}")
            continue

        for model_name, graph_obj in generate_for_size(n):
            made, path = maybe_write_graph(model_name, n, graph_obj, directed=False, force=args.force)
            if made:
                created += 1
                print(f"[OK]   wrote {path.name}")
            else:
                skipped += 1
                print(f"[SKIP] {path.name} already exists")

            if args.directed:
                made, path = maybe_write_graph(model_name, n, graph_obj, directed=True, force=args.force)
                if made:
                    created += 1
                    print(f"[OK]   wrote {path.name}")
                else:
                    skipped += 1
                    print(f"[SKIP] {path.name} already exists")

    print("\nSummary")
    print("-------")
    print(f"Created: {created}")
    print(f"Skipped: {skipped}")


if __name__ == "__main__":
    main()
